
package cn.edu.ahpu.ws.demo.c_cxf_04;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PersonServiceService", targetNamespace = "http://c_cxf_04.demo.ws.ahpu.edu.cn/", wsdlLocation = "http://192.168.1.108:6789/person?wsdl")
public class PersonServiceService
    extends Service
{

    private final static URL PERSONSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.edu.ahpu.ws.demo.c_cxf_04.PersonServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.edu.ahpu.ws.demo.c_cxf_04.PersonServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.1.108:6789/person?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.1.108:6789/person?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PERSONSERVICESERVICE_WSDL_LOCATION = url;
    }

    public PersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServiceService() {
        super(PERSONSERVICESERVICE_WSDL_LOCATION, new QName("http://c_cxf_04.demo.ws.ahpu.edu.cn/", "PersonServiceService"));
    }

    /**
     * 
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonService getPersonServicePort() {
        return super.getPort(new QName("http://c_cxf_04.demo.ws.ahpu.edu.cn/", "PersonServicePort"), PersonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServicePort")
    public PersonService getPersonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://c_cxf_04.demo.ws.ahpu.edu.cn/", "PersonServicePort"), PersonService.class, features);
    }

}
