
package cn.edu.ahpu.ws.demo.c_cxf_04;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PersonService", targetNamespace = "http://c_cxf_04.demo.ws.ahpu.edu.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonService {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.edu.ahpu.ws.demo.c_cxf_04.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPerson", targetNamespace = "http://c_cxf_04.demo.ws.ahpu.edu.cn/", className = "cn.edu.ahpu.ws.demo.c_cxf_04.FindPerson")
    @ResponseWrapper(localName = "findPersonResponse", targetNamespace = "http://c_cxf_04.demo.ws.ahpu.edu.cn/", className = "cn.edu.ahpu.ws.demo.c_cxf_04.FindPersonResponse")
    public Person findPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printPersonInfo", targetNamespace = "http://c_cxf_04.demo.ws.ahpu.edu.cn/", className = "cn.edu.ahpu.ws.demo.c_cxf_04.PrintPersonInfo")
    @ResponseWrapper(localName = "printPersonInfoResponse", targetNamespace = "http://c_cxf_04.demo.ws.ahpu.edu.cn/", className = "cn.edu.ahpu.ws.demo.c_cxf_04.PrintPersonInfoResponse")
    public String printPersonInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

}
